# feast is to store the features for ML models

In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("diabetes.csv")

In [3]:
df.head(2)

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0

In [4]:
predictors_df = df.loc[:,df.columns != 'Outcome']
target_df = df['Outcome']

In [5]:
predictors_df.head(2)

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age
0,6,148,72,35,0,33.6,0.627,50
1,1,85,66,29,0,26.6,0.351,31

### Why we need time stamp for predictiong the current data, and we required the time for prediction when the data get store

In [6]:
timestamps = pd.date_range(end = pd.Timestamp.now(),
                           periods = len(df),freq = 'D').to_frame(name = 'event_timestamp', index = False)

In [7]:
timestamps

               event_timestamp
0   2022-05-06 21:54:01.253863
1   2022-05-07 21:54:01.253863
2   2022-05-08 21:54:01.253863
3   2022-05-09 21:54:01.253863
4   2022-05-10 21:54:01.253863
..                         ...
763 2024-06-07 21:54:01.253863
764 2024-06-08 21:54:01.253863
765 2024-06-09 21:54:01.253863
766 2024-06-10 21:54:01.253863
767 2024-06-11 21:54:01.253863

[768 rows x 1 columns]

In [8]:
# Concate the data with time stamp

In [9]:
predictors_df = pd.concat(objs=[predictors_df,timestamps],axis=1)
target_df = pd.concat(objs=[target_df,timestamps],axis=1)

In [10]:
predictors_df.head(2)

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,event_timestamp
0,6,148,72,35,0,33.6,0.627,50,2022-05-06 21:54:01.253863
1,1,85,66,29,0,26.6,0.351,31,2022-05-07 21:54:01.253863

In [11]:
target_df.head(2)

   Outcome            event_timestamp
0        1 2022-05-06 21:54:01.253863
1        0 2022-05-07 21:54:01.253863

# Create an Unique ID for the data set for prediction

In [12]:
df_len = len(df)
len_list = list(range(df_len))

In [13]:
len_list

[0,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24,
 25,
 26,
 27,
 28,
 29,
 30,
 31,
 32,
 33,
 34,
 35,
 36,
 37,
 38,
 39,
 40,
 41,
 42,
 43,
 44,
 45,
 46,
 47,
 48,
 49,
 50,
 51,
 52,
 53,
 54,
 55,
 56,
 57,
 58,
 59,
 60,
 61,
 62,
 63,
 64,
 65,
 66,
 67,
 68,
 69,
 70,
 71,
 72,
 73,
 74,
 75,
 76,
 77,
 78,
 79,
 80,
 81,
 82,
 83,
 84,
 85,
 86,
 87,
 88,
 89,
 90,
 91,
 92,
 93,
 94,
 95,
 96,
 97,
 98,
 99,
 100,
 101,
 102,
 103,
 104,
 105,
 106,
 107,
 108,
 109,
 110,
 111,
 112,
 113,
 114,
 115,
 116,
 117,
 118,
 119,
 120,
 121,
 122,
 123,
 124,
 125,
 126,
 127,
 128,
 129,
 130,
 131,
 132,
 133,
 134,
 135,
 136,
 137,
 138,
 139,
 140,
 141,
 142,
 143,
 144,
 145,
 146,
 147,
 148,
 149,
 150,
 151,
 152,
 153,
 154,
 155,
 156,
 157,
 158,
 159,
 160,
 161,
 162,
 163,
 164,
 165,
 166,
 167,
 168,
 169,
 170,
 171,
 172,
 173,
 174,
 175,
 176,
 177,
 178,
 179,
 180,
 181,
 182,
 183,
 184,
 185,
 186,
 187,
 188,
 189,
 190,
 191,
 192,
 193,
 194,
 195,
 196,
 197,
 198,
 199,
 200,
 201,
 202,
 203,
 204,
 205,
 206,
 207,
 208,
 209,
 210,
 211,
 212,
 213,
 214,
 215,
 216,
 217,
 218,
 219,
 220,
 221,
 222,
 223,
 224,
 225,
 226,
 227,
 228,
 229,
 230,
 231,
 232,
 233,
 234,
 235,
 236,
 237,
 238,
 239,
 240,
 241,
 242,
 243,
 244,
 245,
 246,
 247,
 248,
 249,
 250,
 251,
 252,
 253,
 254,
 255,
 256,
 257,
 258,
 259,
 260,
 261,
 262,
 263,
 264,
 265,
 266,
 267,
 268,
 269,
 270,
 271,
 272,
 273,
 274,
 275,
 276,
 277,
 278,
 279,
 280,
 281,
 282,
 283,
 284,
 285,
 286,
 287,
 288,
 289,
 290,
 291,
 292,
 293,
 294,
 295,
 296,
 297,
 298,
 299,
 300,
 301,
 302,
 303,
 304,
 305,
 306,
 307,
 308,
 309,
 310,
 311,
 312,
 313,
 314,
 315,
 316,
 317,
 318,
 319,
 320,
 321,
 322,
 323,
 324,
 325,
 326,
 327,
 328,
 329,
 330,
 331,
 332,
 333,
 334,
 335,
 336,
 337,
 338,
 339,
 340,
 341,
 342,
 343,
 344,
 345,
 346,
 347,
 348,
 349,
 350,
 351,
 352,
 353,
 354,
 355,
 356,
 357,
 358,
 359,
 360,
 361,
 362,
 363,
 364,
 365,
 366,
 367,
 368,
 369,
 370,
 371,
 372,
 373,
 374,
 375,
 376,
 377,
 378,
 379,
 380,
 381,
 382,
 383,
 384,
 385,
 386,
 387,
 388,
 389,
 390,
 391,
 392,
 393,
 394,
 395,
 396,
 397,
 398,
 399,
 400,
 401,
 402,
 403,
 404,
 405,
 406,
 407,
 408,
 409,
 410,
 411,
 412,
 413,
 414,
 415,
 416,
 417,
 418,
 419,
 420,
 421,
 422,
 423,
 424,
 425,
 426,
 427,
 428,
 429,
 430,
 431,
 432,
 433,
 434,
 435,
 436,
 437,
 438,
 439,
 440,
 441,
 442,
 443,
 444,
 445,
 446,
 447,
 448,
 449,
 450,
 451,
 452,
 453,
 454,
 455,
 456,
 457,
 458,
 459,
 460,
 461,
 462,
 463,
 464,
 465,
 466,
 467,
 468,
 469,
 470,
 471,
 472,
 473,
 474,
 475,
 476,
 477,
 478,
 479,
 480,
 481,
 482,
 483,
 484,
 485,
 486,
 487,
 488,
 489,
 490,
 491,
 492,
 493,
 494,
 495,
 496,
 497,
 498,
 499,
 500,
 501,
 502,
 503,
 504,
 505,
 506,
 507,
 508,
 509,
 510,
 511,
 512,
 513,
 514,
 515,
 516,
 517,
 518,
 519,
 520,
 521,
 522,
 523,
 524,
 525,
 526,
 527,
 528,
 529,
 530,
 531,
 532,
 533,
 534,
 535,
 536,
 537,
 538,
 539,
 540,
 541,
 542,
 543,
 544,
 545,
 546,
 547,
 548,
 549,
 550,
 551,
 552,
 553,
 554,
 555,
 556,
 557,
 558,
 559,
 560,
 561,
 562,
 563,
 564,
 565,
 566,
 567,
 568,
 569,
 570,
 571,
 572,
 573,
 574,
 575,
 576,
 577,
 578,
 579,
 580,
 581,
 582,
 583,
 584,
 585,
 586,
 587,
 588,
 589,
 590,
 591,
 592,
 593,
 594,
 595,
 596,
 597,
 598,
 599,
 600,
 601,
 602,
 603,
 604,
 605,
 606,
 607,
 608,
 609,
 610,
 611,
 612,
 613,
 614,
 615,
 616,
 617,
 618,
 619,
 620,
 621,
 622,
 623,
 624,
 625,
 626,
 627,
 628,
 629,
 630,
 631,
 632,
 633,
 634,
 635,
 636,
 637,
 638,
 639,
 640,
 641,
 642,
 643,
 644,
 645,
 646,
 647,
 648,
 649,
 650,
 651,
 652,
 653,
 654,
 655,
 656,
 657,
 658,
 659,
 660,
 661,
 662,
 663,
 664,
 665,
 666,
 667,
 668,
 669,
 670,
 671,
 672,
 673,
 674,
 675,
 676,
 677,
 678,
 679,
 680,
 681,
 682,
 683,
 684,
 685,
 686,
 687,
 688,
 689,
 690,
 691,
 692,
 693,
 694,
 695,
 696,
 697,
 698,
 699,
 700,
 701,
 702,
 703,
 704,
 705,
 706,
 707,
 708,
 709,
 710,
 711,
 712,
 713,
 714,
 715,
 716,
 717,
 718,
 719,
 720,
 721,
 722,
 723,
 724,
 725,
 726,
 727,
 728,
 729,
 730,
 731,
 732,
 733,
 734,
 735,
 736,
 737,
 738,
 739,
 740,
 741,
 742,
 743,
 744,
 745,
 746,
 747,
 748,
 749,
 750,
 751,
 752,
 753,
 754,
 755,
 756,
 757,
 758,
 759,
 760,
 761,
 762,
 763,
 764,
 765,
 766,
 767]

In [14]:
patient_ids = pd.DataFrame(data=len_list,columns=['patient_id'])

In [15]:
predictors_df = pd.concat(objs=[predictors_df,patient_ids],axis=1)
target_df = pd.concat(objs=[target_df,patient_ids],axis=1)

In [16]:
# predictors_df.drop(columns=['patient_id'],axis=0,inplace=True)

In [17]:
predictors_df.head(2)

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,event_timestamp,patient_id
0,6,148,72,35,0,33.6,0.627,50,2022-05-06 21:54:01.253863,0
1,1,85,66,29,0,26.6,0.351,31,2022-05-07 21:54:01.253863,1

In [18]:
target_df.head(2)

   Outcome            event_timestamp  patient_id
0        1 2022-05-06 21:54:01.253863           0
1        0 2022-05-07 21:54:01.253863           1

In [19]:
# target_df.drop(columns='patient_id',axis=0,inplace=True)

### Remember Feast accept these fetures of predictors_df in parquet format

In [20]:
predictors_df.to_parquet(path='predictors_df.parquet')
target_df.to_parquet(path='target_df.parquet')

### 2 records are create in our folder name as predictors_df.parquet and target_df.parquet

# Feast starts from Here

In [21]:
!pip install feast

Requirement already satisfied: feast in /Applications/anaconda3/lib/python3.11/site-packages (0.38.0)
Requirement already satisfied: click<9.0.0,>=7.0.0 in /Applications/anaconda3/lib/python3.11/site-packages (from feast) (8.1.7)
Requirement already satisfied: colorama<1,>=0.3.9 in /Applications/anaconda3/lib/python3.11/site-packages (from feast) (0.4.6)
Requirement already satisfied: dill~=0.3.0 in /Applications/anaconda3/lib/python3.11/site-packages (from feast) (0.3.7)
Requirement already satisfied: mypy-protobuf>=3.1 in /Applications/anaconda3/lib/python3.11/site-packages (from feast) (3.6.0)
Requirement already satisfied: Jinja2<4,>=2 in /Applications/anaconda3/lib/python3.11/site-packages (from feast) (3.1.3)
Requirement already satisfied: jsonschema in /Applications/anaconda3/lib/python3.11/site-packages (from feast) (4.19.2)
Requirement already satisfied: mmh3 in /Applications/anaconda3/lib/python3.11/site-packages (from feast) (4.1.0)
Requirement already satisfied: numpy<2,>=1.22 in /Applications/anaconda3/lib/python3.11/site-packages (from feast) (1.26.4)
Requirement already satisfied: pandas<3,>=1.4.3 in /Applications/anaconda3/lib/python3.11/site-packages (from feast) (2.1.4)
Requirement already satisfied: protobuf<5.0.0,>=4.24.0 in /Applications/anaconda3/lib/python3.11/site-packages (from feast) (4.25.3)
Requirement already satisfied: pyarrow>=4 in /Applications/anaconda3/lib/python3.11/site-packages (from feast) (14.0.2)
Requirement already satisfied: pydantic>=2.0.0 in /Applications/anaconda3/lib/python3.11/site-packages (from feast) (2.7.3)
Requirement already satisfied: pygments<3,>=2.12.0 in /Applications/anaconda3/lib/python3.11/site-packages (from feast) (2.15.1)
Requirement already satisfied: PyYAML<7,>=5.4.0 in /Applications/anaconda3/lib/python3.11/site-packages (from feast) (6.0.1)
Requirement already satisfied: requests in /Applications/anaconda3/lib/python3.11/site-packages (from feast) (2.31.0)
Requirement already satisfied: SQLAlchemy>1 in /Applications/anaconda3/lib/python3.11/site-packages (from SQLAlchemy[mypy]>1->feast) (2.0.25)
Requirement already satisfied: tabulate<1,>=0.8.0 in /Applications/anaconda3/lib/python3.11/site-packages (from feast) (0.9.0)
Requirement already satisfied: tenacity<9,>=7 in /Applications/anaconda3/lib/python3.11/site-packages (from feast) (8.2.2)
Requirement already satisfied: toml<1,>=0.10.0 in /Applications/anaconda3/lib/python3.11/site-packages (from feast) (0.10.2)
Requirement already satisfied: tqdm<5,>=4 in /Applications/anaconda3/lib/python3.11/site-packages (from feast) (4.65.0)
Requirement already satisfied: typeguard>=4.0.0 in /Applications/anaconda3/lib/python3.11/site-packages (from feast) (4.3.0)
Requirement already satisfied: fastapi>=0.68.0 in /Applications/anaconda3/lib/python3.11/site-packages (from feast) (0.111.0)
Requirement already satisfied: uvicorn<1,>=0.14.0 in /Applications/anaconda3/lib/python3.11/site-packages (from uvicorn[standard]<1,>=0.14.0->feast) (0.30.1)
Requirement already satisfied: dask>=2024.4.2 in /Applications/anaconda3/lib/python3.11/site-packages (from dask[dataframe]>=2024.4.2->feast) (2024.5.2)
Requirement already satisfied: gunicorn in /Applications/anaconda3/lib/python3.11/site-packages (from feast) (22.0.0)
Requirement already satisfied: cloudpickle>=1.5.0 in /Applications/anaconda3/lib/python3.11/site-packages (from dask>=2024.4.2->dask[dataframe]>=2024.4.2->feast) (2.2.1)
Requirement already satisfied: fsspec>=2021.09.0 in /Applications/anaconda3/lib/python3.11/site-packages (from dask>=2024.4.2->dask[dataframe]>=2024.4.2->feast) (2023.10.0)
Requirement already satisfied: packaging>=20.0 in /Applications/anaconda3/lib/python3.11/site-packages (from dask>=2024.4.2->dask[dataframe]>=2024.4.2->feast) (23.1)
Requirement already satisfied: partd>=1.2.0 in /Applications/anaconda3/lib/python3.11/site-packages (from dask>=2024.4.2->dask[dataframe]>=2024.4.2->feast) (1.4.1)
Requirement already satisfied: toolz>=0.10.0 in /Applications/anaconda3/lib/python3.11/site-packages (from dask>=2024.4.2->dask[dataframe]>=2024.4.2->feast) (0.12.0)
Requirement already satisfied: importlib-metadata>=4.13.0 in /Applications/anaconda3/lib/python3.11/site-packages (from dask>=2024.4.2->dask[dataframe]>=2024.4.2->feast) (7.0.1)
Requirement already satisfied: dask-expr<1.2,>=1.1 in /Applications/anaconda3/lib/python3.11/site-packages (from dask[dataframe]>=2024.4.2->feast) (1.1.2)
Requirement already satisfied: starlette<0.38.0,>=0.37.2 in /Applications/anaconda3/lib/python3.11/site-packages (from fastapi>=0.68.0->feast) (0.37.2)
Requirement already satisfied: typing-extensions>=4.8.0 in /Applications/anaconda3/lib/python3.11/site-packages (from fastapi>=0.68.0->feast) (4.12.2)
Requirement already satisfied: fastapi-cli>=0.0.2 in /Applications/anaconda3/lib/python3.11/site-packages (from fastapi>=0.68.0->feast) (0.0.4)
Requirement already satisfied: httpx>=0.23.0 in /Applications/anaconda3/lib/python3.11/site-packages (from fastapi>=0.68.0->feast) (0.26.0)
Requirement already satisfied: python-multipart>=0.0.7 in /Applications/anaconda3/lib/python3.11/site-packages (from fastapi>=0.68.0->feast) (0.0.9)
Requirement already satisfied: ujson!=4.0.2,!=4.1.0,!=4.2.0,!=4.3.0,!=5.0.0,!=5.1.0,>=4.0.1 in /Applications/anaconda3/lib/python3.11/site-packages (from fastapi>=0.68.0->feast) (5.4.0)
Requirement already satisfied: orjson>=3.2.1 in /Applications/anaconda3/lib/python3.11/site-packages (from fastapi>=0.68.0->feast) (3.10.4)
Requirement already satisfied: email_validator>=2.0.0 in /Applications/anaconda3/lib/python3.11/site-packages (from fastapi>=0.68.0->feast) (2.1.1)
Requirement already satisfied: MarkupSafe>=2.0 in /Applications/anaconda3/lib/python3.11/site-packages (from Jinja2<4,>=2->feast) (2.1.3)
Requirement already satisfied: types-protobuf>=4.24 in /Applications/anaconda3/lib/python3.11/site-packages (from mypy-protobuf>=3.1->feast) (5.26.0.20240422)
Requirement already satisfied: python-dateutil>=2.8.2 in /Applications/anaconda3/lib/python3.11/site-packages (from pandas<3,>=1.4.3->feast) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /Applications/anaconda3/lib/python3.11/site-packages (from pandas<3,>=1.4.3->feast) (2023.3.post1)
Requirement already satisfied: tzdata>=2022.1 in /Applications/anaconda3/lib/python3.11/site-packages (from pandas<3,>=1.4.3->feast) (2023.3)
Requirement already satisfied: annotated-types>=0.4.0 in /Applications/anaconda3/lib/python3.11/site-packages (from pydantic>=2.0.0->feast) (0.7.0)
Requirement already satisfied: pydantic-core==2.18.4 in /Applications/anaconda3/lib/python3.11/site-packages (from pydantic>=2.0.0->feast) (2.18.4)
Requirement already satisfied: mypy>=0.910 in /Applications/anaconda3/lib/python3.11/site-packages (from SQLAlchemy[mypy]>1->feast) (1.8.0)
Requirement already satisfied: h11>=0.8 in /Applications/anaconda3/lib/python3.11/site-packages (from uvicorn<1,>=0.14.0->uvicorn[standard]<1,>=0.14.0->feast) (0.14.0)
Requirement already satisfied: httptools>=0.5.0 in /Applications/anaconda3/lib/python3.11/site-packages (from uvicorn[standard]<1,>=0.14.0->feast) (0.6.1)
Requirement already satisfied: python-dotenv>=0.13 in /Applications/anaconda3/lib/python3.11/site-packages (from uvicorn[standard]<1,>=0.14.0->feast) (0.21.0)
Requirement already satisfied: uvloop!=0.15.0,!=0.15.1,>=0.14.0 in /Applications/anaconda3/lib/python3.11/site-packages (from uvicorn[standard]<1,>=0.14.0->feast) (0.19.0)
Requirement already satisfied: watchfiles>=0.13 in /Applications/anaconda3/lib/python3.11/site-packages (from uvicorn[standard]<1,>=0.14.0->feast) (0.22.0)
Requirement already satisfied: websockets>=10.4 in /Applications/anaconda3/lib/python3.11/site-packages (from uvicorn[standard]<1,>=0.14.0->feast) (12.0)
Requirement already satisfied: attrs>=22.2.0 in /Applications/anaconda3/lib/python3.11/site-packages (from jsonschema->feast) (23.1.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in /Applications/anaconda3/lib/python3.11/site-packages (from jsonschema->feast) (2023.7.1)
Requirement already satisfied: referencing>=0.28.4 in /Applications/anaconda3/lib/python3.11/site-packages (from jsonschema->feast) (0.30.2)
Requirement already satisfied: rpds-py>=0.7.1 in /Applications/anaconda3/lib/python3.11/site-packages (from jsonschema->feast) (0.10.6)
Requirement already satisfied: charset-normalizer<4,>=2 in /Applications/anaconda3/lib/python3.11/site-packages (from requests->feast) (2.0.4)
Requirement already satisfied: idna<4,>=2.5 in /Applications/anaconda3/lib/python3.11/site-packages (from requests->feast) (3.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in /Applications/anaconda3/lib/python3.11/site-packages (from requests->feast) (2.0.7)
Requirement already satisfied: certifi>=2017.4.17 in /Applications/anaconda3/lib/python3.11/site-packages (from requests->feast) (2024.6.2)
Requirement already satisfied: dnspython>=2.0.0 in /Applications/anaconda3/lib/python3.11/site-packages (from email_validator>=2.0.0->fastapi>=0.68.0->feast) (2.6.1)
Requirement already satisfied: typer>=0.12.3 in /Applications/anaconda3/lib/python3.11/site-packages (from fastapi-cli>=0.0.2->fastapi>=0.68.0->feast) (0.12.3)
Requirement already satisfied: anyio in /Applications/anaconda3/lib/python3.11/site-packages (from httpx>=0.23.0->fastapi>=0.68.0->feast) (4.2.0)
Requirement already satisfied: httpcore==1.* in /Applications/anaconda3/lib/python3.11/site-packages (from httpx>=0.23.0->fastapi>=0.68.0->feast) (1.0.5)
Requirement already satisfied: sniffio in /Applications/anaconda3/lib/python3.11/site-packages (from httpx>=0.23.0->fastapi>=0.68.0->feast) (1.3.0)
Requirement already satisfied: zipp>=0.5 in /Applications/anaconda3/lib/python3.11/site-packages (from importlib-metadata>=4.13.0->dask>=2024.4.2->dask[dataframe]>=2024.4.2->feast) (3.17.0)
Requirement already satisfied: mypy-extensions>=1.0.0 in /Applications/anaconda3/lib/python3.11/site-packages (from mypy>=0.910->SQLAlchemy[mypy]>1->feast) (1.0.0)
Requirement already satisfied: locket in /Applications/anaconda3/lib/python3.11/site-packages (from partd>=1.2.0->dask>=2024.4.2->dask[dataframe]>=2024.4.2->feast) (1.0.0)
Requirement already satisfied: six>=1.5 in /Applications/anaconda3/lib/python3.11/site-packages (from python-dateutil>=2.8.2->pandas<3,>=1.4.3->feast) (1.16.0)
Requirement already satisfied: shellingham>=1.3.0 in /Applications/anaconda3/lib/python3.11/site-packages (from typer>=0.12.3->fastapi-cli>=0.0.2->fastapi>=0.68.0->feast) (1.5.4)
Requirement already satisfied: rich>=10.11.0 in /Applications/anaconda3/lib/python3.11/site-packages (from typer>=0.12.3->fastapi-cli>=0.0.2->fastapi>=0.68.0->feast) (13.3.5)
Requirement already satisfied: markdown-it-py<3.0.0,>=2.2.0 in /Applications/anaconda3/lib/python3.11/site-packages (from rich>=10.11.0->typer>=0.12.3->fastapi-cli>=0.0.2->fastapi>=0.68.0->feast) (2.2.0)
Requirement already satisfied: mdurl~=0.1 in /Applications/anaconda3/lib/python3.11/site-packages (from markdown-it-py<3.0.0,>=2.2.0->rich>=10.11.0->typer>=0.12.3->fastapi-cli>=0.0.2->fastapi>=0.68.0->feast) (0.1.0)

In [22]:
!feast version

Feast SDK Version: "0.38.0"

### Feast init -> this will create an repo/folder along with its all required files

In [23]:
pwd

'/Users/bhikipallai/Desktop/python_Anaconda/MLOps/Feast'

In [24]:
!feast init

Creating a new Feast repository in /Users/bhikipallai/Desktop/python_Anaconda/MLOps/Feast/legal_mayfly.

# feast Apply

change drive to feature store

In [25]:
ls

Feast.ipynb            diabetes.csv           target_df.parquet
__pycache__/           legal_mayfly/
amazing_bird/          predictors_df.parquet

In [38]:
cd/Users/bhikipallai/Desktop/python_Anaconda/MLOps/Feast/

/Users/bhikipallai/Desktop/python_Anaconda/MLOps/Feast

In [39]:
pwd

'/Users/bhikipallai/Desktop/python_Anaconda/MLOps/Feast'

In [40]:
ls

Feast.ipynb            diabetes.csv           target_df.parquet
__pycache__/           legal_mayfly/
amazing_bird/          predictors_df.parquet

In [41]:
cd amazing_bird

/Users/bhikipallai/Desktop/python_Anaconda/MLOps/Feast/amazing_bird

In [42]:
ls

README.md     __init__.py   feature_repo/

In [43]:
cd feature_repo

/Users/bhikipallai/Desktop/python_Anaconda/MLOps/Feast/amazing_bird/feature_repo

In [44]:
!feast apply

No changes to registry
No changes to infrastructure

In [45]:
df.head(2)

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0

# Genrate the data set

In [47]:
ls

__init__.py            data/                  feature_store.yaml
__pycache__/           feature_defination.py  test_workflow.py

In [48]:
from feast import FeatureStore
from feast.infra.offline_stores.file_source import SavedDatasetFileStorage

store = FeatureStore(repo_path='.')
# store have the path to get all the feature from the featurestore

entity_df = pd.read_parquet('data/target_df.parquet')
# get the target column

training_data = store.get_historical_features(entity_df=entity_df,
                                             features= ["predictors_df_feature_view:Pregnancies",
                                                        "predictors_df_feature_view:Glucose",
                                                        "predictors_df_feature_view:BloodPressure",
                                                        "predictors_df_feature_view:SkinThickness",
                                                        "predictors_df_feature_view:Insulin",
                                                        "predictors_df_feature_view:BMI",
                                                        "predictors_df_feature_view:DiabetesPedigreeFunction",
                                                        "predictors_df_feature_view:Age",
                                                       ]
                                             )
# here we just assemble the data set with target column and get the features from the feature store, predictors_df_feature_view name of the feature view
dataset = store.create_saved_dataset(from_=training_data,name='diabetes_dataset',
                                     storage=SavedDatasetFileStorage('data/diabetes_dataset1.parquet'))
# create and save the dataset

/Applications/anaconda3/lib/python3.11/site-packages/feast/feature_store.py:1099: RuntimeWarning: Saving dataset is an experimental feature. This API is unstable and it could and most probably will be changed in the future. We do not guarantee that future changes will maintain backward compatibility.
  warnings.warn(

In [51]:
training_data.to_df().head()

,Outcome,event_timestamp,patient_id,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age
0,1,2022-05-06 02:07:17.604227+00:00,0,6,148,72,35,0,33.6,0.627,50
1,0,2022-05-07 02:07:17.604227+00:00,1,1,85,66,29,0,26.6,0.351,31
2,1,2022-05-08 02:07:17.604227+00:00,2,8,183,64,0,0,23.3,0.672,32
3,0,2022-05-09 02:07:17.604227+00:00,3,1,89,66,23,94,28.1,0.167,21
4,1,2022-05-10 02:07:17.604227+00:00,4,0,137,40,35,168,43.1,2.288,33

# Model Training and saving the model

In [52]:
from feast import FeatureStore
from sklearn.linear_model import LogisticRegression
from joblib import dump
from sklearn.model_selection import train_test_split

training_df = training_data.to_df()
# convert the dataset into dataframe

X = training_df.drop(labels=['Outcome','event_timestamp', "patient_id"],axis=1)
y = training_df['Outcome']

X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.3,random_state=21)

log = LogisticRegression(max_iter=200)
log.fit(X_train,y_train)

dump(value=log,filename='model.joblib')

['model.joblib']

# prepare for the online feature store

In [63]:
# Importing dependencies
from feast import FeatureStore
from datetime import datetime, timedelta

# Getting our FeatureStore
store = FeatureStore(repo_path=".")

#store.materialize_incremental(end_date = datetime.now())

# store.materialize(start_date=datetime.utcnow() - timedelta(days=530), end_date=datetime.utcnow() - timedelta(days=10))
store.materialize_incremental(end_date=datetime.now())

Materializing 2 feature views to 2024-06-12 07:11:24+05:30 into the sqlite online store.

target_df_feature_view from 2024-06-02 07:02:22+05:30 to 2024-06-12 07:11:24+05:30:

100%|â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆ| 10/10 [00:00<00:00, 3705.22it/s]

predictors_df_feature_view from 2024-06-02 07:02:22+05:30 to 2024-06-12 12:41:24+05:30:

100%|â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆ| 10/10 [00:00<00:00, 3455.51it/s]

# Get the online feature for predictions

In [76]:
from feast import FeatureStore
store = FeatureStore(repo_path='.')

feast_features = ["predictors_df_feature_view:Pregnancies",
                                                        "predictors_df_feature_view:Glucose",
                                                        "predictors_df_feature_view:BloodPressure",
                                                        "predictors_df_feature_view:SkinThickness",
                                                        "predictors_df_feature_view:Insulin",
                                                        "predictors_df_feature_view:BMI",
                                                        "predictors_df_feature_view:DiabetesPedigreeFunction",
                                                        "predictors_df_feature_view:Age",
                                                       ]

feature = store.get_online_features(features= feast_features,entity_rows=[{"patient_id": 767}, {"patient_id": 766}]).to_df()

# feature_df_one = pd.DataFrame.from_dict(data = feature)

In [77]:
feature.head()

,patient_id,BloodPressure,Glucose,BMI,DiabetesPedigreeFunction,Age,Insulin,Pregnancies,SkinThickness
0,767,70,93,30.4,0.315,23,0,1,31
1,766,60,126,30.1,0.349,47,0,1,0

In [74]:
X_train.head(1)

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age
668,6,98,58,33,190,34.0,0.43,43

# Prediction

In [75]:
from joblib import load

reg = load('model.joblib')

predictions = reg.predict(feature_df_one.drop(columns='patient_id'))
print(predictions)
prediction_probabilities = reg.predict_proba(feature_df_one[sorted(feature_df_one.drop("patient_id", axis=1))])
print(prediction_probabilities)

ValueError: The feature names should match those that were passed during fit.
Feature names must be in the same order as they were in fit.